### PR TITLE
user and role connect

### PR DESCRIPTION
**Pull request by Deonmayon**

### CODE REVIEW

**Comment by Deonmayon** [comment]
can you check it @FC4RICA

**Comment by FC4RICA** [comment]
I​ will​ look into​ it​ first​ thing in​ the​ morning.​ Could​ you​ please​ add​ more​ information​ for​ my​ better​ understanding.​ @Deonmayon

**Comment by Deonmayon** [comment]
In summary, I create role and when register it connect user with role through user_role table.

**Review by FC4RICA — APPROVED** [review]
Everything looks fine. But I have a question about admin creation.

**Pull request merged**
